package core

func MakeConfig() map[string]any {
	return map[string]any{
		"main": map[string]any{
			"name": "FreeMeal",
		},
		"feature": map[string]any{
			"test": map[string]any{
				"options": map[string]any{
					"active": false,
				},
			},
		},
		"options": map[string]any{
			"base": "https://www.themealdb.com/api/json/v1/1",
			"auth": map[string]any{
				"prefix": "Bearer",
			},
			"headers": map[string]any{
				"content-type": "application/json",
			},
			"entity": map[string]any{
				"category": map[string]any{},
				"filter": map[string]any{},
				"latest": map[string]any{},
				"list": map[string]any{},
				"lookup": map[string]any{},
				"random": map[string]any{},
				"randomselection": map[string]any{},
				"search": map[string]any{},
			},
		},
		"entity": map[string]any{
			"category": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "id_category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "str_category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "str_category_description",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "str_category_thumb",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 3,
					},
				},
				"name": "category",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"method": "GET",
								"orig": "/categories.php",
								"parts": []any{
									"categories.php",
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"args": map[string]any{},
								"select": map[string]any{},
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"filter": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "id_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "str_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "str_meal_thumb",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
				},
				"name": "filter",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"example": "Canadian",
											"kind": "query",
											"name": "a",
											"orig": "a",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "Seafood",
											"kind": "query",
											"name": "c",
											"orig": "c",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "chicken_breast",
											"kind": "query",
											"name": "i",
											"orig": "i",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/filter.php",
								"parts": []any{
									"filter.php",
								},
								"select": map[string]any{
									"exist": []any{
										"a",
										"c",
										"i",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"latest": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "date_modified",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "id_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "str_area",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "str_category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 3,
					},
					map[string]any{
						"name": "str_creative_commons_confirmed",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 4,
					},
					map[string]any{
						"name": "str_drink_alternate",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 5,
					},
					map[string]any{
						"name": "str_image_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 6,
					},
					map[string]any{
						"name": "str_ingredient1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 7,
					},
					map[string]any{
						"name": "str_ingredient10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 8,
					},
					map[string]any{
						"name": "str_ingredient11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 9,
					},
					map[string]any{
						"name": "str_ingredient12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 10,
					},
					map[string]any{
						"name": "str_ingredient13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 11,
					},
					map[string]any{
						"name": "str_ingredient14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 12,
					},
					map[string]any{
						"name": "str_ingredient15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 13,
					},
					map[string]any{
						"name": "str_ingredient16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 14,
					},
					map[string]any{
						"name": "str_ingredient17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 15,
					},
					map[string]any{
						"name": "str_ingredient18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 16,
					},
					map[string]any{
						"name": "str_ingredient19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 17,
					},
					map[string]any{
						"name": "str_ingredient2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 18,
					},
					map[string]any{
						"name": "str_ingredient20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 19,
					},
					map[string]any{
						"name": "str_ingredient3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 20,
					},
					map[string]any{
						"name": "str_ingredient4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 21,
					},
					map[string]any{
						"name": "str_ingredient5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 22,
					},
					map[string]any{
						"name": "str_ingredient6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 23,
					},
					map[string]any{
						"name": "str_ingredient7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 24,
					},
					map[string]any{
						"name": "str_ingredient8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 25,
					},
					map[string]any{
						"name": "str_ingredient9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 26,
					},
					map[string]any{
						"name": "str_instruction",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 27,
					},
					map[string]any{
						"name": "str_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 28,
					},
					map[string]any{
						"name": "str_meal_thumb",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 29,
					},
					map[string]any{
						"name": "str_measure1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 30,
					},
					map[string]any{
						"name": "str_measure10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 31,
					},
					map[string]any{
						"name": "str_measure11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 32,
					},
					map[string]any{
						"name": "str_measure12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 33,
					},
					map[string]any{
						"name": "str_measure13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 34,
					},
					map[string]any{
						"name": "str_measure14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 35,
					},
					map[string]any{
						"name": "str_measure15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 36,
					},
					map[string]any{
						"name": "str_measure16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 37,
					},
					map[string]any{
						"name": "str_measure17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 38,
					},
					map[string]any{
						"name": "str_measure18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 39,
					},
					map[string]any{
						"name": "str_measure19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 40,
					},
					map[string]any{
						"name": "str_measure2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 41,
					},
					map[string]any{
						"name": "str_measure20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 42,
					},
					map[string]any{
						"name": "str_measure3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 43,
					},
					map[string]any{
						"name": "str_measure4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 44,
					},
					map[string]any{
						"name": "str_measure5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 45,
					},
					map[string]any{
						"name": "str_measure6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 46,
					},
					map[string]any{
						"name": "str_measure7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 47,
					},
					map[string]any{
						"name": "str_measure8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 48,
					},
					map[string]any{
						"name": "str_measure9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 49,
					},
					map[string]any{
						"name": "str_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 50,
					},
					map[string]any{
						"name": "str_tag",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 51,
					},
					map[string]any{
						"name": "str_youtube",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 52,
					},
				},
				"name": "latest",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"method": "GET",
								"orig": "/latest.php",
								"parts": []any{
									"latest.php",
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"args": map[string]any{},
								"select": map[string]any{},
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"list": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "str_area",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "str_category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "str_ingredient",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
				},
				"name": "list",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"kind": "query",
											"name": "a",
											"orig": "a",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "c",
											"orig": "c",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"kind": "query",
											"name": "i",
											"orig": "i",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/list.php",
								"parts": []any{
									"list.php",
								},
								"select": map[string]any{
									"exist": []any{
										"a",
										"c",
										"i",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"lookup": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "date_modified",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "id_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "str_area",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "str_category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 3,
					},
					map[string]any{
						"name": "str_creative_commons_confirmed",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 4,
					},
					map[string]any{
						"name": "str_drink_alternate",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 5,
					},
					map[string]any{
						"name": "str_image_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 6,
					},
					map[string]any{
						"name": "str_ingredient1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 7,
					},
					map[string]any{
						"name": "str_ingredient10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 8,
					},
					map[string]any{
						"name": "str_ingredient11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 9,
					},
					map[string]any{
						"name": "str_ingredient12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 10,
					},
					map[string]any{
						"name": "str_ingredient13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 11,
					},
					map[string]any{
						"name": "str_ingredient14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 12,
					},
					map[string]any{
						"name": "str_ingredient15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 13,
					},
					map[string]any{
						"name": "str_ingredient16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 14,
					},
					map[string]any{
						"name": "str_ingredient17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 15,
					},
					map[string]any{
						"name": "str_ingredient18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 16,
					},
					map[string]any{
						"name": "str_ingredient19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 17,
					},
					map[string]any{
						"name": "str_ingredient2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 18,
					},
					map[string]any{
						"name": "str_ingredient20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 19,
					},
					map[string]any{
						"name": "str_ingredient3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 20,
					},
					map[string]any{
						"name": "str_ingredient4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 21,
					},
					map[string]any{
						"name": "str_ingredient5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 22,
					},
					map[string]any{
						"name": "str_ingredient6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 23,
					},
					map[string]any{
						"name": "str_ingredient7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 24,
					},
					map[string]any{
						"name": "str_ingredient8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 25,
					},
					map[string]any{
						"name": "str_ingredient9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 26,
					},
					map[string]any{
						"name": "str_instruction",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 27,
					},
					map[string]any{
						"name": "str_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 28,
					},
					map[string]any{
						"name": "str_meal_thumb",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 29,
					},
					map[string]any{
						"name": "str_measure1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 30,
					},
					map[string]any{
						"name": "str_measure10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 31,
					},
					map[string]any{
						"name": "str_measure11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 32,
					},
					map[string]any{
						"name": "str_measure12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 33,
					},
					map[string]any{
						"name": "str_measure13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 34,
					},
					map[string]any{
						"name": "str_measure14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 35,
					},
					map[string]any{
						"name": "str_measure15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 36,
					},
					map[string]any{
						"name": "str_measure16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 37,
					},
					map[string]any{
						"name": "str_measure17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 38,
					},
					map[string]any{
						"name": "str_measure18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 39,
					},
					map[string]any{
						"name": "str_measure19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 40,
					},
					map[string]any{
						"name": "str_measure2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 41,
					},
					map[string]any{
						"name": "str_measure20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 42,
					},
					map[string]any{
						"name": "str_measure3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 43,
					},
					map[string]any{
						"name": "str_measure4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 44,
					},
					map[string]any{
						"name": "str_measure5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 45,
					},
					map[string]any{
						"name": "str_measure6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 46,
					},
					map[string]any{
						"name": "str_measure7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 47,
					},
					map[string]any{
						"name": "str_measure8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 48,
					},
					map[string]any{
						"name": "str_measure9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 49,
					},
					map[string]any{
						"name": "str_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 50,
					},
					map[string]any{
						"name": "str_tag",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 51,
					},
					map[string]any{
						"name": "str_youtube",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 52,
					},
				},
				"name": "lookup",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"example": "52772",
											"kind": "query",
											"name": "i",
											"orig": "i",
											"reqd": true,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/lookup.php",
								"parts": []any{
									"lookup.php",
								},
								"select": map[string]any{
									"exist": []any{
										"i",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"random": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "date_modified",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "id_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "str_area",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "str_category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 3,
					},
					map[string]any{
						"name": "str_creative_commons_confirmed",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 4,
					},
					map[string]any{
						"name": "str_drink_alternate",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 5,
					},
					map[string]any{
						"name": "str_image_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 6,
					},
					map[string]any{
						"name": "str_ingredient1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 7,
					},
					map[string]any{
						"name": "str_ingredient10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 8,
					},
					map[string]any{
						"name": "str_ingredient11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 9,
					},
					map[string]any{
						"name": "str_ingredient12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 10,
					},
					map[string]any{
						"name": "str_ingredient13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 11,
					},
					map[string]any{
						"name": "str_ingredient14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 12,
					},
					map[string]any{
						"name": "str_ingredient15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 13,
					},
					map[string]any{
						"name": "str_ingredient16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 14,
					},
					map[string]any{
						"name": "str_ingredient17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 15,
					},
					map[string]any{
						"name": "str_ingredient18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 16,
					},
					map[string]any{
						"name": "str_ingredient19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 17,
					},
					map[string]any{
						"name": "str_ingredient2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 18,
					},
					map[string]any{
						"name": "str_ingredient20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 19,
					},
					map[string]any{
						"name": "str_ingredient3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 20,
					},
					map[string]any{
						"name": "str_ingredient4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 21,
					},
					map[string]any{
						"name": "str_ingredient5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 22,
					},
					map[string]any{
						"name": "str_ingredient6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 23,
					},
					map[string]any{
						"name": "str_ingredient7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 24,
					},
					map[string]any{
						"name": "str_ingredient8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 25,
					},
					map[string]any{
						"name": "str_ingredient9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 26,
					},
					map[string]any{
						"name": "str_instruction",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 27,
					},
					map[string]any{
						"name": "str_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 28,
					},
					map[string]any{
						"name": "str_meal_thumb",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 29,
					},
					map[string]any{
						"name": "str_measure1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 30,
					},
					map[string]any{
						"name": "str_measure10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 31,
					},
					map[string]any{
						"name": "str_measure11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 32,
					},
					map[string]any{
						"name": "str_measure12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 33,
					},
					map[string]any{
						"name": "str_measure13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 34,
					},
					map[string]any{
						"name": "str_measure14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 35,
					},
					map[string]any{
						"name": "str_measure15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 36,
					},
					map[string]any{
						"name": "str_measure16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 37,
					},
					map[string]any{
						"name": "str_measure17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 38,
					},
					map[string]any{
						"name": "str_measure18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 39,
					},
					map[string]any{
						"name": "str_measure19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 40,
					},
					map[string]any{
						"name": "str_measure2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 41,
					},
					map[string]any{
						"name": "str_measure20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 42,
					},
					map[string]any{
						"name": "str_measure3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 43,
					},
					map[string]any{
						"name": "str_measure4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 44,
					},
					map[string]any{
						"name": "str_measure5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 45,
					},
					map[string]any{
						"name": "str_measure6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 46,
					},
					map[string]any{
						"name": "str_measure7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 47,
					},
					map[string]any{
						"name": "str_measure8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 48,
					},
					map[string]any{
						"name": "str_measure9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 49,
					},
					map[string]any{
						"name": "str_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 50,
					},
					map[string]any{
						"name": "str_tag",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 51,
					},
					map[string]any{
						"name": "str_youtube",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 52,
					},
				},
				"name": "random",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"method": "GET",
								"orig": "/random.php",
								"parts": []any{
									"random.php",
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"args": map[string]any{},
								"select": map[string]any{},
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"randomselection": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "date_modified",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "id_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "str_area",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "str_category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 3,
					},
					map[string]any{
						"name": "str_creative_commons_confirmed",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 4,
					},
					map[string]any{
						"name": "str_drink_alternate",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 5,
					},
					map[string]any{
						"name": "str_image_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 6,
					},
					map[string]any{
						"name": "str_ingredient1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 7,
					},
					map[string]any{
						"name": "str_ingredient10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 8,
					},
					map[string]any{
						"name": "str_ingredient11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 9,
					},
					map[string]any{
						"name": "str_ingredient12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 10,
					},
					map[string]any{
						"name": "str_ingredient13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 11,
					},
					map[string]any{
						"name": "str_ingredient14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 12,
					},
					map[string]any{
						"name": "str_ingredient15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 13,
					},
					map[string]any{
						"name": "str_ingredient16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 14,
					},
					map[string]any{
						"name": "str_ingredient17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 15,
					},
					map[string]any{
						"name": "str_ingredient18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 16,
					},
					map[string]any{
						"name": "str_ingredient19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 17,
					},
					map[string]any{
						"name": "str_ingredient2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 18,
					},
					map[string]any{
						"name": "str_ingredient20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 19,
					},
					map[string]any{
						"name": "str_ingredient3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 20,
					},
					map[string]any{
						"name": "str_ingredient4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 21,
					},
					map[string]any{
						"name": "str_ingredient5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 22,
					},
					map[string]any{
						"name": "str_ingredient6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 23,
					},
					map[string]any{
						"name": "str_ingredient7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 24,
					},
					map[string]any{
						"name": "str_ingredient8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 25,
					},
					map[string]any{
						"name": "str_ingredient9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 26,
					},
					map[string]any{
						"name": "str_instruction",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 27,
					},
					map[string]any{
						"name": "str_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 28,
					},
					map[string]any{
						"name": "str_meal_thumb",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 29,
					},
					map[string]any{
						"name": "str_measure1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 30,
					},
					map[string]any{
						"name": "str_measure10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 31,
					},
					map[string]any{
						"name": "str_measure11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 32,
					},
					map[string]any{
						"name": "str_measure12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 33,
					},
					map[string]any{
						"name": "str_measure13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 34,
					},
					map[string]any{
						"name": "str_measure14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 35,
					},
					map[string]any{
						"name": "str_measure15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 36,
					},
					map[string]any{
						"name": "str_measure16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 37,
					},
					map[string]any{
						"name": "str_measure17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 38,
					},
					map[string]any{
						"name": "str_measure18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 39,
					},
					map[string]any{
						"name": "str_measure19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 40,
					},
					map[string]any{
						"name": "str_measure2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 41,
					},
					map[string]any{
						"name": "str_measure20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 42,
					},
					map[string]any{
						"name": "str_measure3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 43,
					},
					map[string]any{
						"name": "str_measure4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 44,
					},
					map[string]any{
						"name": "str_measure5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 45,
					},
					map[string]any{
						"name": "str_measure6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 46,
					},
					map[string]any{
						"name": "str_measure7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 47,
					},
					map[string]any{
						"name": "str_measure8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 48,
					},
					map[string]any{
						"name": "str_measure9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 49,
					},
					map[string]any{
						"name": "str_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 50,
					},
					map[string]any{
						"name": "str_tag",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 51,
					},
					map[string]any{
						"name": "str_youtube",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 52,
					},
				},
				"name": "randomselection",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"method": "GET",
								"orig": "/randomselection.php",
								"parts": []any{
									"randomselection.php",
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"args": map[string]any{},
								"select": map[string]any{},
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
			"search": map[string]any{
				"fields": []any{
					map[string]any{
						"name": "date_modified",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 0,
					},
					map[string]any{
						"name": "id_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 1,
					},
					map[string]any{
						"name": "str_area",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 2,
					},
					map[string]any{
						"name": "str_category",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 3,
					},
					map[string]any{
						"name": "str_creative_commons_confirmed",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 4,
					},
					map[string]any{
						"name": "str_drink_alternate",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 5,
					},
					map[string]any{
						"name": "str_image_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 6,
					},
					map[string]any{
						"name": "str_ingredient1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 7,
					},
					map[string]any{
						"name": "str_ingredient10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 8,
					},
					map[string]any{
						"name": "str_ingredient11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 9,
					},
					map[string]any{
						"name": "str_ingredient12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 10,
					},
					map[string]any{
						"name": "str_ingredient13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 11,
					},
					map[string]any{
						"name": "str_ingredient14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 12,
					},
					map[string]any{
						"name": "str_ingredient15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 13,
					},
					map[string]any{
						"name": "str_ingredient16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 14,
					},
					map[string]any{
						"name": "str_ingredient17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 15,
					},
					map[string]any{
						"name": "str_ingredient18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 16,
					},
					map[string]any{
						"name": "str_ingredient19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 17,
					},
					map[string]any{
						"name": "str_ingredient2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 18,
					},
					map[string]any{
						"name": "str_ingredient20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 19,
					},
					map[string]any{
						"name": "str_ingredient3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 20,
					},
					map[string]any{
						"name": "str_ingredient4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 21,
					},
					map[string]any{
						"name": "str_ingredient5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 22,
					},
					map[string]any{
						"name": "str_ingredient6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 23,
					},
					map[string]any{
						"name": "str_ingredient7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 24,
					},
					map[string]any{
						"name": "str_ingredient8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 25,
					},
					map[string]any{
						"name": "str_ingredient9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 26,
					},
					map[string]any{
						"name": "str_instruction",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 27,
					},
					map[string]any{
						"name": "str_meal",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 28,
					},
					map[string]any{
						"name": "str_meal_thumb",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 29,
					},
					map[string]any{
						"name": "str_measure1",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 30,
					},
					map[string]any{
						"name": "str_measure10",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 31,
					},
					map[string]any{
						"name": "str_measure11",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 32,
					},
					map[string]any{
						"name": "str_measure12",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 33,
					},
					map[string]any{
						"name": "str_measure13",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 34,
					},
					map[string]any{
						"name": "str_measure14",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 35,
					},
					map[string]any{
						"name": "str_measure15",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 36,
					},
					map[string]any{
						"name": "str_measure16",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 37,
					},
					map[string]any{
						"name": "str_measure17",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 38,
					},
					map[string]any{
						"name": "str_measure18",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 39,
					},
					map[string]any{
						"name": "str_measure19",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 40,
					},
					map[string]any{
						"name": "str_measure2",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 41,
					},
					map[string]any{
						"name": "str_measure20",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 42,
					},
					map[string]any{
						"name": "str_measure3",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 43,
					},
					map[string]any{
						"name": "str_measure4",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 44,
					},
					map[string]any{
						"name": "str_measure5",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 45,
					},
					map[string]any{
						"name": "str_measure6",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 46,
					},
					map[string]any{
						"name": "str_measure7",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 47,
					},
					map[string]any{
						"name": "str_measure8",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 48,
					},
					map[string]any{
						"name": "str_measure9",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 49,
					},
					map[string]any{
						"name": "str_source",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 50,
					},
					map[string]any{
						"name": "str_tag",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 51,
					},
					map[string]any{
						"name": "str_youtube",
						"req": false,
						"type": "`$STRING`",
						"active": true,
						"index$": 52,
					},
				},
				"name": "search",
				"op": map[string]any{
					"list": map[string]any{
						"name": "list",
						"points": []any{
							map[string]any{
								"args": map[string]any{
									"query": []any{
										map[string]any{
											"example": "a",
											"kind": "query",
											"name": "f",
											"orig": "f",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
										map[string]any{
											"example": "Arrabiata",
											"kind": "query",
											"name": "s",
											"orig": "s",
											"reqd": false,
											"type": "`$STRING`",
											"active": true,
										},
									},
								},
								"method": "GET",
								"orig": "/search.php",
								"parts": []any{
									"search.php",
								},
								"select": map[string]any{
									"exist": []any{
										"f",
										"s",
									},
								},
								"transform": map[string]any{
									"req": "`reqdata`",
									"res": "`body`",
								},
								"active": true,
								"index$": 0,
							},
						},
						"input": "data",
						"key$": "list",
					},
				},
				"relations": map[string]any{
					"ancestors": []any{},
				},
			},
		},
	}
}

func makeFeature(name string) Feature {
	switch name {
	case "test":
		if NewTestFeatureFunc != nil {
			return NewTestFeatureFunc()
		}
	default:
		if NewBaseFeatureFunc != nil {
			return NewBaseFeatureFunc()
		}
	}
	return nil
}
