# FreeMeal SDK configuration

module FreeMealConfig
  def self.make_config
    {
      "main" => {
        "name" => "FreeMeal",
      },
      "feature" => {
        "test" => {
          "options" => {
            "active" => false,
          },
        },
      },
      "options" => {
        "base" => "https://www.themealdb.com/api/json/v1/1",
        "auth" => {
          "prefix" => "Bearer",
        },
        "headers" => {
          "content-type" => "application/json",
        },
        "entity" => {
          "category" => {},
          "filter" => {},
          "latest" => {},
          "list" => {},
          "lookup" => {},
          "random" => {},
          "randomselection" => {},
          "search" => {},
        },
      },
      "entity" => {
        "category" => {
          "fields" => [
            {
              "name" => "id_category",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "str_category",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "str_category_description",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
            {
              "name" => "str_category_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 3,
            },
          ],
          "name" => "category",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "method" => "GET",
                  "orig" => "/categories.php",
                  "parts" => [
                    "categories.php",
                  ],
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "args" => {},
                  "select" => {},
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "filter" => {
          "fields" => [
            {
              "name" => "id_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "str_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "str_meal_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
          ],
          "name" => "filter",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "args" => {
                    "query" => [
                      {
                        "example" => "Canadian",
                        "kind" => "query",
                        "name" => "a",
                        "orig" => "a",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "Seafood",
                        "kind" => "query",
                        "name" => "c",
                        "orig" => "c",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "chicken_breast",
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/filter.php",
                  "parts" => [
                    "filter.php",
                  ],
                  "select" => {
                    "exist" => [
                      "a",
                      "c",
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "latest" => {
          "fields" => [
            {
              "name" => "date_modified",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "id_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "str_area",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
            {
              "name" => "str_category",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 3,
            },
            {
              "name" => "str_creative_commons_confirmed",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 4,
            },
            {
              "name" => "str_drink_alternate",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 5,
            },
            {
              "name" => "str_image_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 6,
            },
            {
              "name" => "str_ingredient1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 7,
            },
            {
              "name" => "str_ingredient10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 8,
            },
            {
              "name" => "str_ingredient11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 9,
            },
            {
              "name" => "str_ingredient12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 10,
            },
            {
              "name" => "str_ingredient13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 11,
            },
            {
              "name" => "str_ingredient14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 12,
            },
            {
              "name" => "str_ingredient15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 13,
            },
            {
              "name" => "str_ingredient16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 14,
            },
            {
              "name" => "str_ingredient17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 15,
            },
            {
              "name" => "str_ingredient18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 16,
            },
            {
              "name" => "str_ingredient19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 17,
            },
            {
              "name" => "str_ingredient2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 18,
            },
            {
              "name" => "str_ingredient20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 19,
            },
            {
              "name" => "str_ingredient3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 20,
            },
            {
              "name" => "str_ingredient4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 21,
            },
            {
              "name" => "str_ingredient5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 22,
            },
            {
              "name" => "str_ingredient6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 23,
            },
            {
              "name" => "str_ingredient7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 24,
            },
            {
              "name" => "str_ingredient8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 25,
            },
            {
              "name" => "str_ingredient9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 26,
            },
            {
              "name" => "str_instruction",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 27,
            },
            {
              "name" => "str_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 28,
            },
            {
              "name" => "str_meal_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 29,
            },
            {
              "name" => "str_measure1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 30,
            },
            {
              "name" => "str_measure10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 31,
            },
            {
              "name" => "str_measure11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 32,
            },
            {
              "name" => "str_measure12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 33,
            },
            {
              "name" => "str_measure13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 34,
            },
            {
              "name" => "str_measure14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 35,
            },
            {
              "name" => "str_measure15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 36,
            },
            {
              "name" => "str_measure16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 37,
            },
            {
              "name" => "str_measure17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 38,
            },
            {
              "name" => "str_measure18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 39,
            },
            {
              "name" => "str_measure19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 40,
            },
            {
              "name" => "str_measure2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 41,
            },
            {
              "name" => "str_measure20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 42,
            },
            {
              "name" => "str_measure3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 43,
            },
            {
              "name" => "str_measure4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 44,
            },
            {
              "name" => "str_measure5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 45,
            },
            {
              "name" => "str_measure6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 46,
            },
            {
              "name" => "str_measure7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 47,
            },
            {
              "name" => "str_measure8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 48,
            },
            {
              "name" => "str_measure9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 49,
            },
            {
              "name" => "str_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 50,
            },
            {
              "name" => "str_tag",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 51,
            },
            {
              "name" => "str_youtube",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 52,
            },
          ],
          "name" => "latest",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "method" => "GET",
                  "orig" => "/latest.php",
                  "parts" => [
                    "latest.php",
                  ],
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "args" => {},
                  "select" => {},
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "list" => {
          "fields" => [
            {
              "name" => "str_area",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "str_category",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "str_ingredient",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
          ],
          "name" => "list",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "args" => {
                    "query" => [
                      {
                        "kind" => "query",
                        "name" => "a",
                        "orig" => "a",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "c",
                        "orig" => "c",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/list.php",
                  "parts" => [
                    "list.php",
                  ],
                  "select" => {
                    "exist" => [
                      "a",
                      "c",
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "lookup" => {
          "fields" => [
            {
              "name" => "date_modified",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "id_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "str_area",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
            {
              "name" => "str_category",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 3,
            },
            {
              "name" => "str_creative_commons_confirmed",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 4,
            },
            {
              "name" => "str_drink_alternate",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 5,
            },
            {
              "name" => "str_image_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 6,
            },
            {
              "name" => "str_ingredient1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 7,
            },
            {
              "name" => "str_ingredient10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 8,
            },
            {
              "name" => "str_ingredient11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 9,
            },
            {
              "name" => "str_ingredient12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 10,
            },
            {
              "name" => "str_ingredient13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 11,
            },
            {
              "name" => "str_ingredient14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 12,
            },
            {
              "name" => "str_ingredient15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 13,
            },
            {
              "name" => "str_ingredient16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 14,
            },
            {
              "name" => "str_ingredient17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 15,
            },
            {
              "name" => "str_ingredient18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 16,
            },
            {
              "name" => "str_ingredient19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 17,
            },
            {
              "name" => "str_ingredient2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 18,
            },
            {
              "name" => "str_ingredient20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 19,
            },
            {
              "name" => "str_ingredient3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 20,
            },
            {
              "name" => "str_ingredient4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 21,
            },
            {
              "name" => "str_ingredient5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 22,
            },
            {
              "name" => "str_ingredient6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 23,
            },
            {
              "name" => "str_ingredient7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 24,
            },
            {
              "name" => "str_ingredient8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 25,
            },
            {
              "name" => "str_ingredient9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 26,
            },
            {
              "name" => "str_instruction",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 27,
            },
            {
              "name" => "str_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 28,
            },
            {
              "name" => "str_meal_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 29,
            },
            {
              "name" => "str_measure1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 30,
            },
            {
              "name" => "str_measure10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 31,
            },
            {
              "name" => "str_measure11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 32,
            },
            {
              "name" => "str_measure12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 33,
            },
            {
              "name" => "str_measure13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 34,
            },
            {
              "name" => "str_measure14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 35,
            },
            {
              "name" => "str_measure15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 36,
            },
            {
              "name" => "str_measure16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 37,
            },
            {
              "name" => "str_measure17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 38,
            },
            {
              "name" => "str_measure18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 39,
            },
            {
              "name" => "str_measure19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 40,
            },
            {
              "name" => "str_measure2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 41,
            },
            {
              "name" => "str_measure20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 42,
            },
            {
              "name" => "str_measure3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 43,
            },
            {
              "name" => "str_measure4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 44,
            },
            {
              "name" => "str_measure5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 45,
            },
            {
              "name" => "str_measure6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 46,
            },
            {
              "name" => "str_measure7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 47,
            },
            {
              "name" => "str_measure8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 48,
            },
            {
              "name" => "str_measure9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 49,
            },
            {
              "name" => "str_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 50,
            },
            {
              "name" => "str_tag",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 51,
            },
            {
              "name" => "str_youtube",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 52,
            },
          ],
          "name" => "lookup",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "args" => {
                    "query" => [
                      {
                        "example" => "52772",
                        "kind" => "query",
                        "name" => "i",
                        "orig" => "i",
                        "reqd" => true,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/lookup.php",
                  "parts" => [
                    "lookup.php",
                  ],
                  "select" => {
                    "exist" => [
                      "i",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "random" => {
          "fields" => [
            {
              "name" => "date_modified",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "id_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "str_area",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
            {
              "name" => "str_category",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 3,
            },
            {
              "name" => "str_creative_commons_confirmed",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 4,
            },
            {
              "name" => "str_drink_alternate",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 5,
            },
            {
              "name" => "str_image_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 6,
            },
            {
              "name" => "str_ingredient1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 7,
            },
            {
              "name" => "str_ingredient10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 8,
            },
            {
              "name" => "str_ingredient11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 9,
            },
            {
              "name" => "str_ingredient12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 10,
            },
            {
              "name" => "str_ingredient13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 11,
            },
            {
              "name" => "str_ingredient14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 12,
            },
            {
              "name" => "str_ingredient15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 13,
            },
            {
              "name" => "str_ingredient16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 14,
            },
            {
              "name" => "str_ingredient17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 15,
            },
            {
              "name" => "str_ingredient18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 16,
            },
            {
              "name" => "str_ingredient19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 17,
            },
            {
              "name" => "str_ingredient2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 18,
            },
            {
              "name" => "str_ingredient20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 19,
            },
            {
              "name" => "str_ingredient3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 20,
            },
            {
              "name" => "str_ingredient4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 21,
            },
            {
              "name" => "str_ingredient5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 22,
            },
            {
              "name" => "str_ingredient6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 23,
            },
            {
              "name" => "str_ingredient7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 24,
            },
            {
              "name" => "str_ingredient8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 25,
            },
            {
              "name" => "str_ingredient9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 26,
            },
            {
              "name" => "str_instruction",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 27,
            },
            {
              "name" => "str_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 28,
            },
            {
              "name" => "str_meal_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 29,
            },
            {
              "name" => "str_measure1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 30,
            },
            {
              "name" => "str_measure10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 31,
            },
            {
              "name" => "str_measure11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 32,
            },
            {
              "name" => "str_measure12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 33,
            },
            {
              "name" => "str_measure13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 34,
            },
            {
              "name" => "str_measure14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 35,
            },
            {
              "name" => "str_measure15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 36,
            },
            {
              "name" => "str_measure16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 37,
            },
            {
              "name" => "str_measure17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 38,
            },
            {
              "name" => "str_measure18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 39,
            },
            {
              "name" => "str_measure19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 40,
            },
            {
              "name" => "str_measure2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 41,
            },
            {
              "name" => "str_measure20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 42,
            },
            {
              "name" => "str_measure3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 43,
            },
            {
              "name" => "str_measure4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 44,
            },
            {
              "name" => "str_measure5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 45,
            },
            {
              "name" => "str_measure6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 46,
            },
            {
              "name" => "str_measure7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 47,
            },
            {
              "name" => "str_measure8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 48,
            },
            {
              "name" => "str_measure9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 49,
            },
            {
              "name" => "str_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 50,
            },
            {
              "name" => "str_tag",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 51,
            },
            {
              "name" => "str_youtube",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 52,
            },
          ],
          "name" => "random",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "method" => "GET",
                  "orig" => "/random.php",
                  "parts" => [
                    "random.php",
                  ],
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "args" => {},
                  "select" => {},
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "randomselection" => {
          "fields" => [
            {
              "name" => "date_modified",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "id_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "str_area",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
            {
              "name" => "str_category",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 3,
            },
            {
              "name" => "str_creative_commons_confirmed",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 4,
            },
            {
              "name" => "str_drink_alternate",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 5,
            },
            {
              "name" => "str_image_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 6,
            },
            {
              "name" => "str_ingredient1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 7,
            },
            {
              "name" => "str_ingredient10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 8,
            },
            {
              "name" => "str_ingredient11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 9,
            },
            {
              "name" => "str_ingredient12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 10,
            },
            {
              "name" => "str_ingredient13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 11,
            },
            {
              "name" => "str_ingredient14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 12,
            },
            {
              "name" => "str_ingredient15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 13,
            },
            {
              "name" => "str_ingredient16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 14,
            },
            {
              "name" => "str_ingredient17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 15,
            },
            {
              "name" => "str_ingredient18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 16,
            },
            {
              "name" => "str_ingredient19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 17,
            },
            {
              "name" => "str_ingredient2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 18,
            },
            {
              "name" => "str_ingredient20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 19,
            },
            {
              "name" => "str_ingredient3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 20,
            },
            {
              "name" => "str_ingredient4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 21,
            },
            {
              "name" => "str_ingredient5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 22,
            },
            {
              "name" => "str_ingredient6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 23,
            },
            {
              "name" => "str_ingredient7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 24,
            },
            {
              "name" => "str_ingredient8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 25,
            },
            {
              "name" => "str_ingredient9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 26,
            },
            {
              "name" => "str_instruction",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 27,
            },
            {
              "name" => "str_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 28,
            },
            {
              "name" => "str_meal_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 29,
            },
            {
              "name" => "str_measure1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 30,
            },
            {
              "name" => "str_measure10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 31,
            },
            {
              "name" => "str_measure11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 32,
            },
            {
              "name" => "str_measure12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 33,
            },
            {
              "name" => "str_measure13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 34,
            },
            {
              "name" => "str_measure14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 35,
            },
            {
              "name" => "str_measure15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 36,
            },
            {
              "name" => "str_measure16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 37,
            },
            {
              "name" => "str_measure17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 38,
            },
            {
              "name" => "str_measure18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 39,
            },
            {
              "name" => "str_measure19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 40,
            },
            {
              "name" => "str_measure2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 41,
            },
            {
              "name" => "str_measure20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 42,
            },
            {
              "name" => "str_measure3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 43,
            },
            {
              "name" => "str_measure4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 44,
            },
            {
              "name" => "str_measure5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 45,
            },
            {
              "name" => "str_measure6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 46,
            },
            {
              "name" => "str_measure7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 47,
            },
            {
              "name" => "str_measure8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 48,
            },
            {
              "name" => "str_measure9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 49,
            },
            {
              "name" => "str_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 50,
            },
            {
              "name" => "str_tag",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 51,
            },
            {
              "name" => "str_youtube",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 52,
            },
          ],
          "name" => "randomselection",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "method" => "GET",
                  "orig" => "/randomselection.php",
                  "parts" => [
                    "randomselection.php",
                  ],
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "args" => {},
                  "select" => {},
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
        "search" => {
          "fields" => [
            {
              "name" => "date_modified",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 0,
            },
            {
              "name" => "id_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 1,
            },
            {
              "name" => "str_area",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 2,
            },
            {
              "name" => "str_category",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 3,
            },
            {
              "name" => "str_creative_commons_confirmed",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 4,
            },
            {
              "name" => "str_drink_alternate",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 5,
            },
            {
              "name" => "str_image_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 6,
            },
            {
              "name" => "str_ingredient1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 7,
            },
            {
              "name" => "str_ingredient10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 8,
            },
            {
              "name" => "str_ingredient11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 9,
            },
            {
              "name" => "str_ingredient12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 10,
            },
            {
              "name" => "str_ingredient13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 11,
            },
            {
              "name" => "str_ingredient14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 12,
            },
            {
              "name" => "str_ingredient15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 13,
            },
            {
              "name" => "str_ingredient16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 14,
            },
            {
              "name" => "str_ingredient17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 15,
            },
            {
              "name" => "str_ingredient18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 16,
            },
            {
              "name" => "str_ingredient19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 17,
            },
            {
              "name" => "str_ingredient2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 18,
            },
            {
              "name" => "str_ingredient20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 19,
            },
            {
              "name" => "str_ingredient3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 20,
            },
            {
              "name" => "str_ingredient4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 21,
            },
            {
              "name" => "str_ingredient5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 22,
            },
            {
              "name" => "str_ingredient6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 23,
            },
            {
              "name" => "str_ingredient7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 24,
            },
            {
              "name" => "str_ingredient8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 25,
            },
            {
              "name" => "str_ingredient9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 26,
            },
            {
              "name" => "str_instruction",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 27,
            },
            {
              "name" => "str_meal",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 28,
            },
            {
              "name" => "str_meal_thumb",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 29,
            },
            {
              "name" => "str_measure1",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 30,
            },
            {
              "name" => "str_measure10",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 31,
            },
            {
              "name" => "str_measure11",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 32,
            },
            {
              "name" => "str_measure12",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 33,
            },
            {
              "name" => "str_measure13",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 34,
            },
            {
              "name" => "str_measure14",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 35,
            },
            {
              "name" => "str_measure15",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 36,
            },
            {
              "name" => "str_measure16",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 37,
            },
            {
              "name" => "str_measure17",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 38,
            },
            {
              "name" => "str_measure18",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 39,
            },
            {
              "name" => "str_measure19",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 40,
            },
            {
              "name" => "str_measure2",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 41,
            },
            {
              "name" => "str_measure20",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 42,
            },
            {
              "name" => "str_measure3",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 43,
            },
            {
              "name" => "str_measure4",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 44,
            },
            {
              "name" => "str_measure5",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 45,
            },
            {
              "name" => "str_measure6",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 46,
            },
            {
              "name" => "str_measure7",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 47,
            },
            {
              "name" => "str_measure8",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 48,
            },
            {
              "name" => "str_measure9",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 49,
            },
            {
              "name" => "str_source",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 50,
            },
            {
              "name" => "str_tag",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 51,
            },
            {
              "name" => "str_youtube",
              "req" => false,
              "type" => "`$STRING`",
              "active" => true,
              "index$" => 52,
            },
          ],
          "name" => "search",
          "op" => {
            "list" => {
              "name" => "list",
              "points" => [
                {
                  "args" => {
                    "query" => [
                      {
                        "example" => "a",
                        "kind" => "query",
                        "name" => "f",
                        "orig" => "f",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                      {
                        "example" => "Arrabiata",
                        "kind" => "query",
                        "name" => "s",
                        "orig" => "s",
                        "reqd" => false,
                        "type" => "`$STRING`",
                        "active" => true,
                      },
                    ],
                  },
                  "method" => "GET",
                  "orig" => "/search.php",
                  "parts" => [
                    "search.php",
                  ],
                  "select" => {
                    "exist" => [
                      "f",
                      "s",
                    ],
                  },
                  "transform" => {
                    "req" => "`reqdata`",
                    "res" => "`body`",
                  },
                  "active" => true,
                  "index$" => 0,
                },
              ],
              "input" => "data",
              "key$" => "list",
            },
          },
          "relations" => {
            "ancestors" => [],
          },
        },
      },
    }
  end


  def self.make_feature(name)
    require_relative 'features'
    FreeMealFeatures.make_feature(name)
  end
end
