<?php
declare(strict_types=1);

// FreeMeal SDK configuration

class FreeMealConfig
{
    public static function make_config(): array
    {
        return [
            "main" => [
                "name" => "FreeMeal",
            ],
            "feature" => [
                "test" => [
          'options' => [
            'active' => false,
          ],
        ],
            ],
            "options" => [
                "base" => "https://www.themealdb.com/api/json/v1/1",
                "auth" => [
                    "prefix" => "",
                ],
                "headers" => [
          'content-type' => 'application/json',
        ],
                "entity" => [
                    "category" => [],
                    "filter" => [],
                    "latest" => [],
                    "list" => [],
                    "lookup" => [],
                    "random" => [],
                    "randomselection" => [],
                    "search" => [],
                ],
            ],
            "entity" => [
        'category' => [
          'fields' => [
            [
              'active' => true,
              'name' => 'idCategory',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 0,
            ],
            [
              'active' => true,
              'name' => 'strCategory',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 1,
            ],
            [
              'active' => true,
              'name' => 'strCategoryDescription',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 2,
            ],
            [
              'active' => true,
              'name' => 'strCategoryThumb',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 3,
            ],
          ],
          'name' => 'category',
          'op' => [
            'list' => [
              'input' => 'data',
              'name' => 'list',
              'points' => [
                [
                  'active' => true,
                  'args' => [],
                  'kind' => 'http',
                  'method' => 'GET',
                  'orig' => '/categories.php',
                  'parts' => [
                    'categories.php',
                  ],
                  'select' => [],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body.categories`',
                  ],
                  'index$' => 0,
                ],
              ],
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'filter' => [
          'fields' => [
            [
              'active' => true,
              'name' => 'idMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 0,
            ],
            [
              'active' => true,
              'name' => 'strMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 1,
            ],
            [
              'active' => true,
              'name' => 'strMealThumb',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 2,
            ],
          ],
          'name' => 'filter',
          'op' => [
            'list' => [
              'input' => 'data',
              'name' => 'list',
              'points' => [
                [
                  'active' => true,
                  'args' => [
                    'query' => [
                      [
                        'active' => true,
                        'example' => 'Canadian',
                        'kind' => 'query',
                        'name' => 'a',
                        'orig' => 'a',
                        'reqd' => false,
                        'type' => '`$STRING`',
                      ],
                      [
                        'active' => true,
                        'example' => 'Seafood',
                        'kind' => 'query',
                        'name' => 'c',
                        'orig' => 'c',
                        'reqd' => false,
                        'type' => '`$STRING`',
                      ],
                      [
                        'active' => true,
                        'example' => 'chicken_breast',
                        'kind' => 'query',
                        'name' => 'i',
                        'orig' => 'i',
                        'reqd' => false,
                        'type' => '`$STRING`',
                      ],
                    ],
                  ],
                  'kind' => 'http',
                  'method' => 'GET',
                  'orig' => '/filter.php',
                  'parts' => [
                    'filter.php',
                  ],
                  'select' => [
                    'exist' => [
                      'a',
                      'c',
                      'i',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body.meals`',
                  ],
                  'index$' => 0,
                ],
              ],
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'latest' => [
          'fields' => [
            [
              'active' => true,
              'name' => 'dateModified',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 0,
            ],
            [
              'active' => true,
              'name' => 'idMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 1,
            ],
            [
              'active' => true,
              'name' => 'strArea',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 2,
            ],
            [
              'active' => true,
              'name' => 'strCategory',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 3,
            ],
            [
              'active' => true,
              'name' => 'strCreativeCommonsConfirmed',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 4,
            ],
            [
              'active' => true,
              'name' => 'strDrinkAlternate',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 5,
            ],
            [
              'active' => true,
              'name' => 'strImageSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 6,
            ],
            [
              'active' => true,
              'name' => 'strIngredient1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 7,
            ],
            [
              'active' => true,
              'name' => 'strIngredient10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 8,
            ],
            [
              'active' => true,
              'name' => 'strIngredient11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 9,
            ],
            [
              'active' => true,
              'name' => 'strIngredient12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 10,
            ],
            [
              'active' => true,
              'name' => 'strIngredient13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 11,
            ],
            [
              'active' => true,
              'name' => 'strIngredient14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 12,
            ],
            [
              'active' => true,
              'name' => 'strIngredient15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 13,
            ],
            [
              'active' => true,
              'name' => 'strIngredient16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 14,
            ],
            [
              'active' => true,
              'name' => 'strIngredient17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 15,
            ],
            [
              'active' => true,
              'name' => 'strIngredient18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 16,
            ],
            [
              'active' => true,
              'name' => 'strIngredient19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 17,
            ],
            [
              'active' => true,
              'name' => 'strIngredient2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 18,
            ],
            [
              'active' => true,
              'name' => 'strIngredient20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 19,
            ],
            [
              'active' => true,
              'name' => 'strIngredient3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 20,
            ],
            [
              'active' => true,
              'name' => 'strIngredient4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 21,
            ],
            [
              'active' => true,
              'name' => 'strIngredient5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 22,
            ],
            [
              'active' => true,
              'name' => 'strIngredient6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 23,
            ],
            [
              'active' => true,
              'name' => 'strIngredient7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 24,
            ],
            [
              'active' => true,
              'name' => 'strIngredient8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 25,
            ],
            [
              'active' => true,
              'name' => 'strIngredient9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 26,
            ],
            [
              'active' => true,
              'name' => 'strInstructions',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 27,
            ],
            [
              'active' => true,
              'name' => 'strMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 28,
            ],
            [
              'active' => true,
              'name' => 'strMealThumb',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 29,
            ],
            [
              'active' => true,
              'name' => 'strMeasure1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 30,
            ],
            [
              'active' => true,
              'name' => 'strMeasure10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 31,
            ],
            [
              'active' => true,
              'name' => 'strMeasure11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 32,
            ],
            [
              'active' => true,
              'name' => 'strMeasure12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 33,
            ],
            [
              'active' => true,
              'name' => 'strMeasure13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 34,
            ],
            [
              'active' => true,
              'name' => 'strMeasure14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 35,
            ],
            [
              'active' => true,
              'name' => 'strMeasure15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 36,
            ],
            [
              'active' => true,
              'name' => 'strMeasure16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 37,
            ],
            [
              'active' => true,
              'name' => 'strMeasure17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 38,
            ],
            [
              'active' => true,
              'name' => 'strMeasure18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 39,
            ],
            [
              'active' => true,
              'name' => 'strMeasure19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 40,
            ],
            [
              'active' => true,
              'name' => 'strMeasure2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 41,
            ],
            [
              'active' => true,
              'name' => 'strMeasure20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 42,
            ],
            [
              'active' => true,
              'name' => 'strMeasure3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 43,
            ],
            [
              'active' => true,
              'name' => 'strMeasure4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 44,
            ],
            [
              'active' => true,
              'name' => 'strMeasure5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 45,
            ],
            [
              'active' => true,
              'name' => 'strMeasure6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 46,
            ],
            [
              'active' => true,
              'name' => 'strMeasure7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 47,
            ],
            [
              'active' => true,
              'name' => 'strMeasure8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 48,
            ],
            [
              'active' => true,
              'name' => 'strMeasure9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 49,
            ],
            [
              'active' => true,
              'name' => 'strSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 50,
            ],
            [
              'active' => true,
              'name' => 'strTags',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 51,
            ],
            [
              'active' => true,
              'name' => 'strYoutube',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 52,
            ],
          ],
          'name' => 'latest',
          'op' => [
            'list' => [
              'input' => 'data',
              'name' => 'list',
              'points' => [
                [
                  'active' => true,
                  'args' => [],
                  'kind' => 'http',
                  'method' => 'GET',
                  'orig' => '/latest.php',
                  'parts' => [
                    'latest.php',
                  ],
                  'select' => [],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body.meals`',
                  ],
                  'index$' => 0,
                ],
              ],
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'list' => [
          'fields' => [
            [
              'active' => true,
              'name' => 'strArea',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 0,
            ],
            [
              'active' => true,
              'name' => 'strCategory',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 1,
            ],
            [
              'active' => true,
              'name' => 'strIngredient',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 2,
            ],
          ],
          'name' => 'list',
          'op' => [
            'list' => [
              'input' => 'data',
              'name' => 'list',
              'points' => [
                [
                  'active' => true,
                  'args' => [
                    'query' => [
                      [
                        'active' => true,
                        'kind' => 'query',
                        'name' => 'a',
                        'orig' => 'a',
                        'reqd' => false,
                        'type' => '`$STRING`',
                      ],
                      [
                        'active' => true,
                        'kind' => 'query',
                        'name' => 'c',
                        'orig' => 'c',
                        'reqd' => false,
                        'type' => '`$STRING`',
                      ],
                      [
                        'active' => true,
                        'kind' => 'query',
                        'name' => 'i',
                        'orig' => 'i',
                        'reqd' => false,
                        'type' => '`$STRING`',
                      ],
                    ],
                  ],
                  'kind' => 'http',
                  'method' => 'GET',
                  'orig' => '/list.php',
                  'parts' => [
                    'list.php',
                  ],
                  'select' => [
                    'exist' => [
                      'a',
                      'c',
                      'i',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body.meals`',
                  ],
                  'index$' => 0,
                ],
              ],
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'lookup' => [
          'fields' => [
            [
              'active' => true,
              'name' => 'dateModified',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 0,
            ],
            [
              'active' => true,
              'name' => 'idMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 1,
            ],
            [
              'active' => true,
              'name' => 'strArea',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 2,
            ],
            [
              'active' => true,
              'name' => 'strCategory',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 3,
            ],
            [
              'active' => true,
              'name' => 'strCreativeCommonsConfirmed',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 4,
            ],
            [
              'active' => true,
              'name' => 'strDrinkAlternate',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 5,
            ],
            [
              'active' => true,
              'name' => 'strImageSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 6,
            ],
            [
              'active' => true,
              'name' => 'strIngredient1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 7,
            ],
            [
              'active' => true,
              'name' => 'strIngredient10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 8,
            ],
            [
              'active' => true,
              'name' => 'strIngredient11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 9,
            ],
            [
              'active' => true,
              'name' => 'strIngredient12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 10,
            ],
            [
              'active' => true,
              'name' => 'strIngredient13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 11,
            ],
            [
              'active' => true,
              'name' => 'strIngredient14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 12,
            ],
            [
              'active' => true,
              'name' => 'strIngredient15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 13,
            ],
            [
              'active' => true,
              'name' => 'strIngredient16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 14,
            ],
            [
              'active' => true,
              'name' => 'strIngredient17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 15,
            ],
            [
              'active' => true,
              'name' => 'strIngredient18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 16,
            ],
            [
              'active' => true,
              'name' => 'strIngredient19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 17,
            ],
            [
              'active' => true,
              'name' => 'strIngredient2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 18,
            ],
            [
              'active' => true,
              'name' => 'strIngredient20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 19,
            ],
            [
              'active' => true,
              'name' => 'strIngredient3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 20,
            ],
            [
              'active' => true,
              'name' => 'strIngredient4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 21,
            ],
            [
              'active' => true,
              'name' => 'strIngredient5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 22,
            ],
            [
              'active' => true,
              'name' => 'strIngredient6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 23,
            ],
            [
              'active' => true,
              'name' => 'strIngredient7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 24,
            ],
            [
              'active' => true,
              'name' => 'strIngredient8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 25,
            ],
            [
              'active' => true,
              'name' => 'strIngredient9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 26,
            ],
            [
              'active' => true,
              'name' => 'strInstructions',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 27,
            ],
            [
              'active' => true,
              'name' => 'strMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 28,
            ],
            [
              'active' => true,
              'name' => 'strMealThumb',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 29,
            ],
            [
              'active' => true,
              'name' => 'strMeasure1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 30,
            ],
            [
              'active' => true,
              'name' => 'strMeasure10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 31,
            ],
            [
              'active' => true,
              'name' => 'strMeasure11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 32,
            ],
            [
              'active' => true,
              'name' => 'strMeasure12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 33,
            ],
            [
              'active' => true,
              'name' => 'strMeasure13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 34,
            ],
            [
              'active' => true,
              'name' => 'strMeasure14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 35,
            ],
            [
              'active' => true,
              'name' => 'strMeasure15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 36,
            ],
            [
              'active' => true,
              'name' => 'strMeasure16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 37,
            ],
            [
              'active' => true,
              'name' => 'strMeasure17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 38,
            ],
            [
              'active' => true,
              'name' => 'strMeasure18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 39,
            ],
            [
              'active' => true,
              'name' => 'strMeasure19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 40,
            ],
            [
              'active' => true,
              'name' => 'strMeasure2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 41,
            ],
            [
              'active' => true,
              'name' => 'strMeasure20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 42,
            ],
            [
              'active' => true,
              'name' => 'strMeasure3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 43,
            ],
            [
              'active' => true,
              'name' => 'strMeasure4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 44,
            ],
            [
              'active' => true,
              'name' => 'strMeasure5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 45,
            ],
            [
              'active' => true,
              'name' => 'strMeasure6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 46,
            ],
            [
              'active' => true,
              'name' => 'strMeasure7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 47,
            ],
            [
              'active' => true,
              'name' => 'strMeasure8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 48,
            ],
            [
              'active' => true,
              'name' => 'strMeasure9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 49,
            ],
            [
              'active' => true,
              'name' => 'strSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 50,
            ],
            [
              'active' => true,
              'name' => 'strTags',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 51,
            ],
            [
              'active' => true,
              'name' => 'strYoutube',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 52,
            ],
          ],
          'name' => 'lookup',
          'op' => [
            'list' => [
              'input' => 'data',
              'name' => 'list',
              'points' => [
                [
                  'active' => true,
                  'args' => [
                    'query' => [
                      [
                        'active' => true,
                        'example' => '52772',
                        'kind' => 'query',
                        'name' => 'i',
                        'orig' => 'i',
                        'reqd' => true,
                        'type' => '`$STRING`',
                      ],
                    ],
                  ],
                  'kind' => 'http',
                  'method' => 'GET',
                  'orig' => '/lookup.php',
                  'parts' => [
                    'lookup.php',
                  ],
                  'select' => [
                    'exist' => [
                      'i',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body.meals`',
                  ],
                  'index$' => 0,
                ],
              ],
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'random' => [
          'fields' => [
            [
              'active' => true,
              'name' => 'dateModified',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 0,
            ],
            [
              'active' => true,
              'name' => 'idMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 1,
            ],
            [
              'active' => true,
              'name' => 'strArea',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 2,
            ],
            [
              'active' => true,
              'name' => 'strCategory',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 3,
            ],
            [
              'active' => true,
              'name' => 'strCreativeCommonsConfirmed',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 4,
            ],
            [
              'active' => true,
              'name' => 'strDrinkAlternate',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 5,
            ],
            [
              'active' => true,
              'name' => 'strImageSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 6,
            ],
            [
              'active' => true,
              'name' => 'strIngredient1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 7,
            ],
            [
              'active' => true,
              'name' => 'strIngredient10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 8,
            ],
            [
              'active' => true,
              'name' => 'strIngredient11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 9,
            ],
            [
              'active' => true,
              'name' => 'strIngredient12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 10,
            ],
            [
              'active' => true,
              'name' => 'strIngredient13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 11,
            ],
            [
              'active' => true,
              'name' => 'strIngredient14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 12,
            ],
            [
              'active' => true,
              'name' => 'strIngredient15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 13,
            ],
            [
              'active' => true,
              'name' => 'strIngredient16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 14,
            ],
            [
              'active' => true,
              'name' => 'strIngredient17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 15,
            ],
            [
              'active' => true,
              'name' => 'strIngredient18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 16,
            ],
            [
              'active' => true,
              'name' => 'strIngredient19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 17,
            ],
            [
              'active' => true,
              'name' => 'strIngredient2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 18,
            ],
            [
              'active' => true,
              'name' => 'strIngredient20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 19,
            ],
            [
              'active' => true,
              'name' => 'strIngredient3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 20,
            ],
            [
              'active' => true,
              'name' => 'strIngredient4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 21,
            ],
            [
              'active' => true,
              'name' => 'strIngredient5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 22,
            ],
            [
              'active' => true,
              'name' => 'strIngredient6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 23,
            ],
            [
              'active' => true,
              'name' => 'strIngredient7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 24,
            ],
            [
              'active' => true,
              'name' => 'strIngredient8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 25,
            ],
            [
              'active' => true,
              'name' => 'strIngredient9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 26,
            ],
            [
              'active' => true,
              'name' => 'strInstructions',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 27,
            ],
            [
              'active' => true,
              'name' => 'strMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 28,
            ],
            [
              'active' => true,
              'name' => 'strMealThumb',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 29,
            ],
            [
              'active' => true,
              'name' => 'strMeasure1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 30,
            ],
            [
              'active' => true,
              'name' => 'strMeasure10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 31,
            ],
            [
              'active' => true,
              'name' => 'strMeasure11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 32,
            ],
            [
              'active' => true,
              'name' => 'strMeasure12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 33,
            ],
            [
              'active' => true,
              'name' => 'strMeasure13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 34,
            ],
            [
              'active' => true,
              'name' => 'strMeasure14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 35,
            ],
            [
              'active' => true,
              'name' => 'strMeasure15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 36,
            ],
            [
              'active' => true,
              'name' => 'strMeasure16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 37,
            ],
            [
              'active' => true,
              'name' => 'strMeasure17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 38,
            ],
            [
              'active' => true,
              'name' => 'strMeasure18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 39,
            ],
            [
              'active' => true,
              'name' => 'strMeasure19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 40,
            ],
            [
              'active' => true,
              'name' => 'strMeasure2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 41,
            ],
            [
              'active' => true,
              'name' => 'strMeasure20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 42,
            ],
            [
              'active' => true,
              'name' => 'strMeasure3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 43,
            ],
            [
              'active' => true,
              'name' => 'strMeasure4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 44,
            ],
            [
              'active' => true,
              'name' => 'strMeasure5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 45,
            ],
            [
              'active' => true,
              'name' => 'strMeasure6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 46,
            ],
            [
              'active' => true,
              'name' => 'strMeasure7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 47,
            ],
            [
              'active' => true,
              'name' => 'strMeasure8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 48,
            ],
            [
              'active' => true,
              'name' => 'strMeasure9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 49,
            ],
            [
              'active' => true,
              'name' => 'strSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 50,
            ],
            [
              'active' => true,
              'name' => 'strTags',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 51,
            ],
            [
              'active' => true,
              'name' => 'strYoutube',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 52,
            ],
          ],
          'name' => 'random',
          'op' => [
            'list' => [
              'input' => 'data',
              'name' => 'list',
              'points' => [
                [
                  'active' => true,
                  'args' => [],
                  'kind' => 'http',
                  'method' => 'GET',
                  'orig' => '/random.php',
                  'parts' => [
                    'random.php',
                  ],
                  'select' => [],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body.meals`',
                  ],
                  'index$' => 0,
                ],
              ],
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'randomselection' => [
          'fields' => [
            [
              'active' => true,
              'name' => 'dateModified',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 0,
            ],
            [
              'active' => true,
              'name' => 'idMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 1,
            ],
            [
              'active' => true,
              'name' => 'strArea',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 2,
            ],
            [
              'active' => true,
              'name' => 'strCategory',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 3,
            ],
            [
              'active' => true,
              'name' => 'strCreativeCommonsConfirmed',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 4,
            ],
            [
              'active' => true,
              'name' => 'strDrinkAlternate',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 5,
            ],
            [
              'active' => true,
              'name' => 'strImageSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 6,
            ],
            [
              'active' => true,
              'name' => 'strIngredient1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 7,
            ],
            [
              'active' => true,
              'name' => 'strIngredient10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 8,
            ],
            [
              'active' => true,
              'name' => 'strIngredient11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 9,
            ],
            [
              'active' => true,
              'name' => 'strIngredient12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 10,
            ],
            [
              'active' => true,
              'name' => 'strIngredient13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 11,
            ],
            [
              'active' => true,
              'name' => 'strIngredient14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 12,
            ],
            [
              'active' => true,
              'name' => 'strIngredient15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 13,
            ],
            [
              'active' => true,
              'name' => 'strIngredient16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 14,
            ],
            [
              'active' => true,
              'name' => 'strIngredient17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 15,
            ],
            [
              'active' => true,
              'name' => 'strIngredient18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 16,
            ],
            [
              'active' => true,
              'name' => 'strIngredient19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 17,
            ],
            [
              'active' => true,
              'name' => 'strIngredient2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 18,
            ],
            [
              'active' => true,
              'name' => 'strIngredient20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 19,
            ],
            [
              'active' => true,
              'name' => 'strIngredient3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 20,
            ],
            [
              'active' => true,
              'name' => 'strIngredient4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 21,
            ],
            [
              'active' => true,
              'name' => 'strIngredient5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 22,
            ],
            [
              'active' => true,
              'name' => 'strIngredient6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 23,
            ],
            [
              'active' => true,
              'name' => 'strIngredient7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 24,
            ],
            [
              'active' => true,
              'name' => 'strIngredient8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 25,
            ],
            [
              'active' => true,
              'name' => 'strIngredient9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 26,
            ],
            [
              'active' => true,
              'name' => 'strInstructions',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 27,
            ],
            [
              'active' => true,
              'name' => 'strMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 28,
            ],
            [
              'active' => true,
              'name' => 'strMealThumb',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 29,
            ],
            [
              'active' => true,
              'name' => 'strMeasure1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 30,
            ],
            [
              'active' => true,
              'name' => 'strMeasure10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 31,
            ],
            [
              'active' => true,
              'name' => 'strMeasure11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 32,
            ],
            [
              'active' => true,
              'name' => 'strMeasure12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 33,
            ],
            [
              'active' => true,
              'name' => 'strMeasure13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 34,
            ],
            [
              'active' => true,
              'name' => 'strMeasure14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 35,
            ],
            [
              'active' => true,
              'name' => 'strMeasure15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 36,
            ],
            [
              'active' => true,
              'name' => 'strMeasure16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 37,
            ],
            [
              'active' => true,
              'name' => 'strMeasure17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 38,
            ],
            [
              'active' => true,
              'name' => 'strMeasure18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 39,
            ],
            [
              'active' => true,
              'name' => 'strMeasure19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 40,
            ],
            [
              'active' => true,
              'name' => 'strMeasure2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 41,
            ],
            [
              'active' => true,
              'name' => 'strMeasure20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 42,
            ],
            [
              'active' => true,
              'name' => 'strMeasure3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 43,
            ],
            [
              'active' => true,
              'name' => 'strMeasure4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 44,
            ],
            [
              'active' => true,
              'name' => 'strMeasure5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 45,
            ],
            [
              'active' => true,
              'name' => 'strMeasure6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 46,
            ],
            [
              'active' => true,
              'name' => 'strMeasure7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 47,
            ],
            [
              'active' => true,
              'name' => 'strMeasure8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 48,
            ],
            [
              'active' => true,
              'name' => 'strMeasure9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 49,
            ],
            [
              'active' => true,
              'name' => 'strSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 50,
            ],
            [
              'active' => true,
              'name' => 'strTags',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 51,
            ],
            [
              'active' => true,
              'name' => 'strYoutube',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 52,
            ],
          ],
          'name' => 'randomselection',
          'op' => [
            'list' => [
              'input' => 'data',
              'name' => 'list',
              'points' => [
                [
                  'active' => true,
                  'args' => [],
                  'kind' => 'http',
                  'method' => 'GET',
                  'orig' => '/randomselection.php',
                  'parts' => [
                    'randomselection.php',
                  ],
                  'select' => [],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body.meals`',
                  ],
                  'index$' => 0,
                ],
              ],
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
        'search' => [
          'fields' => [
            [
              'active' => true,
              'name' => 'dateModified',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 0,
            ],
            [
              'active' => true,
              'name' => 'idMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 1,
            ],
            [
              'active' => true,
              'name' => 'strArea',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 2,
            ],
            [
              'active' => true,
              'name' => 'strCategory',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 3,
            ],
            [
              'active' => true,
              'name' => 'strCreativeCommonsConfirmed',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 4,
            ],
            [
              'active' => true,
              'name' => 'strDrinkAlternate',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 5,
            ],
            [
              'active' => true,
              'name' => 'strImageSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 6,
            ],
            [
              'active' => true,
              'name' => 'strIngredient1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 7,
            ],
            [
              'active' => true,
              'name' => 'strIngredient10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 8,
            ],
            [
              'active' => true,
              'name' => 'strIngredient11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 9,
            ],
            [
              'active' => true,
              'name' => 'strIngredient12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 10,
            ],
            [
              'active' => true,
              'name' => 'strIngredient13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 11,
            ],
            [
              'active' => true,
              'name' => 'strIngredient14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 12,
            ],
            [
              'active' => true,
              'name' => 'strIngredient15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 13,
            ],
            [
              'active' => true,
              'name' => 'strIngredient16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 14,
            ],
            [
              'active' => true,
              'name' => 'strIngredient17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 15,
            ],
            [
              'active' => true,
              'name' => 'strIngredient18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 16,
            ],
            [
              'active' => true,
              'name' => 'strIngredient19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 17,
            ],
            [
              'active' => true,
              'name' => 'strIngredient2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 18,
            ],
            [
              'active' => true,
              'name' => 'strIngredient20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 19,
            ],
            [
              'active' => true,
              'name' => 'strIngredient3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 20,
            ],
            [
              'active' => true,
              'name' => 'strIngredient4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 21,
            ],
            [
              'active' => true,
              'name' => 'strIngredient5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 22,
            ],
            [
              'active' => true,
              'name' => 'strIngredient6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 23,
            ],
            [
              'active' => true,
              'name' => 'strIngredient7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 24,
            ],
            [
              'active' => true,
              'name' => 'strIngredient8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 25,
            ],
            [
              'active' => true,
              'name' => 'strIngredient9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 26,
            ],
            [
              'active' => true,
              'name' => 'strInstructions',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 27,
            ],
            [
              'active' => true,
              'name' => 'strMeal',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 28,
            ],
            [
              'active' => true,
              'name' => 'strMealThumb',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 29,
            ],
            [
              'active' => true,
              'name' => 'strMeasure1',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 30,
            ],
            [
              'active' => true,
              'name' => 'strMeasure10',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 31,
            ],
            [
              'active' => true,
              'name' => 'strMeasure11',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 32,
            ],
            [
              'active' => true,
              'name' => 'strMeasure12',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 33,
            ],
            [
              'active' => true,
              'name' => 'strMeasure13',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 34,
            ],
            [
              'active' => true,
              'name' => 'strMeasure14',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 35,
            ],
            [
              'active' => true,
              'name' => 'strMeasure15',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 36,
            ],
            [
              'active' => true,
              'name' => 'strMeasure16',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 37,
            ],
            [
              'active' => true,
              'name' => 'strMeasure17',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 38,
            ],
            [
              'active' => true,
              'name' => 'strMeasure18',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 39,
            ],
            [
              'active' => true,
              'name' => 'strMeasure19',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 40,
            ],
            [
              'active' => true,
              'name' => 'strMeasure2',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 41,
            ],
            [
              'active' => true,
              'name' => 'strMeasure20',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 42,
            ],
            [
              'active' => true,
              'name' => 'strMeasure3',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 43,
            ],
            [
              'active' => true,
              'name' => 'strMeasure4',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 44,
            ],
            [
              'active' => true,
              'name' => 'strMeasure5',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 45,
            ],
            [
              'active' => true,
              'name' => 'strMeasure6',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 46,
            ],
            [
              'active' => true,
              'name' => 'strMeasure7',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 47,
            ],
            [
              'active' => true,
              'name' => 'strMeasure8',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 48,
            ],
            [
              'active' => true,
              'name' => 'strMeasure9',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 49,
            ],
            [
              'active' => true,
              'name' => 'strSource',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 50,
            ],
            [
              'active' => true,
              'name' => 'strTags',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 51,
            ],
            [
              'active' => true,
              'name' => 'strYoutube',
              'req' => false,
              'type' => '`$STRING`',
              'index$' => 52,
            ],
          ],
          'name' => 'search',
          'op' => [
            'list' => [
              'input' => 'data',
              'name' => 'list',
              'points' => [
                [
                  'active' => true,
                  'args' => [
                    'query' => [
                      [
                        'active' => true,
                        'example' => 'a',
                        'kind' => 'query',
                        'name' => 'f',
                        'orig' => 'f',
                        'reqd' => false,
                        'type' => '`$STRING`',
                      ],
                      [
                        'active' => true,
                        'example' => 'Arrabiata',
                        'kind' => 'query',
                        'name' => 's',
                        'orig' => 's',
                        'reqd' => false,
                        'type' => '`$STRING`',
                      ],
                    ],
                  ],
                  'kind' => 'http',
                  'method' => 'GET',
                  'orig' => '/search.php',
                  'parts' => [
                    'search.php',
                  ],
                  'select' => [
                    'exist' => [
                      'f',
                      's',
                    ],
                  ],
                  'transform' => [
                    'req' => '`reqdata`',
                    'res' => '`body.meals`',
                  ],
                  'index$' => 0,
                ],
              ],
              'key$' => 'list',
            ],
          ],
          'relations' => [
            'ancestors' => [],
          ],
        ],
      ],
        ];
    }


    public static function make_feature(string $name)
    {
        require_once __DIR__ . '/features.php';
        return FreeMealFeatures::make_feature($name);
    }
}
